// automatically generated by the FlatBuffers compiler, do not modify

import { flatbuffers } from './flatbuffers.js';
/**
 * @const
 * @namespace
 */
var QAService = QAService || {};

/**
 * @const
 * @namespace
 */
QAService.Payloads = QAService.Payloads || {};

/**
 * @enum {number}
 */
QAService.Payloads.AnyPayload = {
  NONE: 0,
  QARequest: 1,
  QAResponse: 2
};

/**
 * @enum {string}
 */
QAService.Payloads.AnyPayloadName = {
  '0': 'NONE',
  '1': 'QARequest',
  '2': 'QAResponse'
};

/**
 * @constructor
 */
QAService.Payloads.QARequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {QAService.Payloads.QARequest}
 */
QAService.Payloads.QARequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {QAService.Payloads.QARequest=} obj
 * @returns {QAService.Payloads.QARequest}
 */
QAService.Payloads.QARequest.getRootAsQARequest = function(bb, obj) {
  return (obj || new QAService.Payloads.QARequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {QAService.Payloads.QARequest=} obj
 * @returns {QAService.Payloads.QARequest}
 */
QAService.Payloads.QARequest.getSizePrefixedRootAsQARequest = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new QAService.Payloads.QARequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
QAService.Payloads.QARequest.prototype.question = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
QAService.Payloads.QARequest.prototype.context = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
QAService.Payloads.QARequest.startQARequest = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} questionOffset
 */
QAService.Payloads.QARequest.addQuestion = function(builder, questionOffset) {
  builder.addFieldOffset(0, questionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} contextOffset
 */
QAService.Payloads.QARequest.addContext = function(builder, contextOffset) {
  builder.addFieldOffset(1, contextOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
QAService.Payloads.QARequest.endQARequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} questionOffset
 * @param {flatbuffers.Offset} contextOffset
 * @returns {flatbuffers.Offset}
 */
QAService.Payloads.QARequest.createQARequest = function(builder, questionOffset, contextOffset) {
  QAService.Payloads.QARequest.startQARequest(builder);
  QAService.Payloads.QARequest.addQuestion(builder, questionOffset);
  QAService.Payloads.QARequest.addContext(builder, contextOffset);
  return QAService.Payloads.QARequest.endQARequest(builder);
}

/**
 * @constructor
 */
QAService.Payloads.QAResponse = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {QAService.Payloads.QAResponse}
 */
QAService.Payloads.QAResponse.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {QAService.Payloads.QAResponse=} obj
 * @returns {QAService.Payloads.QAResponse}
 */
QAService.Payloads.QAResponse.getRootAsQAResponse = function(bb, obj) {
  return (obj || new QAService.Payloads.QAResponse).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {QAService.Payloads.QAResponse=} obj
 * @returns {QAService.Payloads.QAResponse}
 */
QAService.Payloads.QAResponse.getSizePrefixedRootAsQAResponse = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new QAService.Payloads.QAResponse).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
QAService.Payloads.QAResponse.prototype.answer = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
QAService.Payloads.QAResponse.startQAResponse = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} answerOffset
 */
QAService.Payloads.QAResponse.addAnswer = function(builder, answerOffset) {
  builder.addFieldOffset(0, answerOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
QAService.Payloads.QAResponse.endQAResponse = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} answerOffset
 * @returns {flatbuffers.Offset}
 */
QAService.Payloads.QAResponse.createQAResponse = function(builder, answerOffset) {
  QAService.Payloads.QAResponse.startQAResponse(builder);
  QAService.Payloads.QAResponse.addAnswer(builder, answerOffset);
  return QAService.Payloads.QAResponse.endQAResponse(builder);
}

/**
 * @constructor
 */
QAService.Payloads.Root = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {QAService.Payloads.Root}
 */
QAService.Payloads.Root.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {QAService.Payloads.Root=} obj
 * @returns {QAService.Payloads.Root}
 */
QAService.Payloads.Root.getRootAsRoot = function(bb, obj) {
  return (obj || new QAService.Payloads.Root).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {QAService.Payloads.Root=} obj
 * @returns {QAService.Payloads.Root}
 */
QAService.Payloads.Root.getSizePrefixedRootAsRoot = function(bb, obj) {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new QAService.Payloads.Root).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {boolean}
 */
QAService.Payloads.Root.bufferHasIdentifier = function(bb) {
  return bb.__has_identifier('QASV');
};

/**
 * @returns {QAService.Payloads.AnyPayload}
 */
QAService.Payloads.Root.prototype.payloadType = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {QAService.Payloads.AnyPayload} */ (this.bb.readUint8(this.bb_pos + offset)) : QAService.Payloads.AnyPayload.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
QAService.Payloads.Root.prototype.payload = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
QAService.Payloads.Root.startRoot = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {QAService.Payloads.AnyPayload} payloadType
 */
QAService.Payloads.Root.addPayloadType = function(builder, payloadType) {
  builder.addFieldInt8(0, payloadType, QAService.Payloads.AnyPayload.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} payloadOffset
 */
QAService.Payloads.Root.addPayload = function(builder, payloadOffset) {
  builder.addFieldOffset(1, payloadOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
QAService.Payloads.Root.endRoot = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
QAService.Payloads.Root.finishRootBuffer = function(builder, offset) {
  builder.finish(offset, 'QASV');
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
QAService.Payloads.Root.finishSizePrefixedRootBuffer = function(builder, offset) {
  builder.finish(offset, 'QASV', true);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {QAService.Payloads.AnyPayload} payloadType
 * @param {flatbuffers.Offset} payloadOffset
 * @returns {flatbuffers.Offset}
 */
QAService.Payloads.Root.createRoot = function(builder, payloadType, payloadOffset) {
  QAService.Payloads.Root.startRoot(builder);
  QAService.Payloads.Root.addPayloadType(builder, payloadType);
  QAService.Payloads.Root.addPayload(builder, payloadOffset);
  return QAService.Payloads.Root.endRoot(builder);
}

export default QAService;
