# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Payloads

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class QARequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsQARequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = QARequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def QARequestBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x51\x41\x53\x56", size_prefixed=size_prefixed)

    # QARequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # QARequest
    def Question(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # QARequest
    def Context(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def QARequestStart(builder): builder.StartObject(2)
def QARequestAddQuestion(builder, question): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(question), 0)
def QARequestAddContext(builder, context): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(context), 0)
def QARequestEnd(builder): return builder.EndObject()
