# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Payloads

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class QAResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsQAResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = QAResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def QAResponseBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x51\x41\x53\x56", size_prefixed=size_prefixed)

    # QAResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # QAResponse
    def Answer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def QAResponseStart(builder): builder.StartObject(1)
def QAResponseAddAnswer(builder, answer): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(answer), 0)
def QAResponseEnd(builder): return builder.EndObject()
