# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Payloads

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Root(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsRoot(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Root()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def RootBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x51\x41\x53\x56", size_prefixed=size_prefixed)

    # Root
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Root
    def PayloadType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Root
    def Payload(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def RootStart(builder): builder.StartObject(2)
def RootAddPayloadType(builder, payloadType): builder.PrependUint8Slot(0, payloadType, 0)
def RootAddPayload(builder, payload): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)
def RootEnd(builder): return builder.EndObject()
